### ISSUE TITLE
Non 1:1 photos display weird

### ISSUE THREAD

**Issue by mrbirl** [mrbirl/SurfTracker#6]
The photos look crap - they're being forced into 1:1 format and it's messing them up.

Should handle photos better - crop if sticking with 1:1 format.

**Comment by NQuinn27** [comment]
Quick fix -  change imageView.contentMode to .ScaleAspectFit, and set the background colour of the imageView to black - you will get a proper aspect with black letterbox. 

Play around with contentMode to get other kinds of fill (scaleAspectFill will fill the imageView, but keep aspect ratio)

**Comment by mrbirl** [comment]
Sweet, cheers @NQuinn27! I'll check that out right now :)

**Comment by mrbirl** [comment]
Done - thanks @NQuinn27
